In [707]:
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, SnowballStemmer

In [708]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [709]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace=True)

In [710]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [711]:
df['v2']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [712]:
new = []
lmtz = WordNetLemmatizer()

for text in df['v2'].astype(str):  
    temp = re.sub(r'[^a-zA-Z]', ' ', text.lower())  # Remove non-alphabetic characters
    words = temp.split()  # Split into words
    lemmatized_words = [lmtz.lemmatize(word, pos='v') for word in words]  # Lemmatize all words as verbs
    new.append(" ".join(lemmatized_words))  # Join words back into a sentence

print(new[4])  # Print first processed text

nah i don t think he go to usf he live around here though


In [713]:
print(df['v2'][4])

Nah I don't think he goes to usf, he lives around here though


In [714]:
df['new_text'] = new

In [715]:
df

v1                                                 v2  \
0      ham  Go until jurong point, crazy.. Available only ...   
1      ham                      Ok lar... Joking wif u oni...   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3      ham  U dun say so early hor... U c already then say...   
4      ham  Nah I don't think he goes to usf, he lives aro...   
...    ...                                                ...   
5567  spam  This is the 2nd time we have tried 2 contact u...   
5568   ham              Will Ì_ b going to esplanade fr home?   
5569   ham  Pity, * was in mood for that. So...any other s...   
5570   ham  The guy did some bitching but I acted like i'd...   
5571   ham                         Rofl. Its true to its name   

                                               new_text  
0     go until jurong point crazy available only in ...  
1                                 ok lar joke wif u oni  
2     free entry in a wkly comp to win fa cup final ...  
3           u dun say so early hor u c already then say  
4     nah i don t think he go to usf he live around ...  
...                                                 ...  
5567  this be the nd time we have try contact u u ha...  
5568                     will b go to esplanade fr home  
5569  pity be in mood for that so any other suggestions  
5570  the guy do some bitch but i act like i d be in...  
5571                          rofl its true to its name  

[5572 rows x 3 columns]

In [716]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [717]:
tfidf = TfidfVectorizer(max_features=500)

In [718]:
vec = tfidf.fit_transform(new).toarray()
np.set_printoptions(threshold=np.inf)

In [719]:
vec[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [720]:
[i for i in vec[0] if i!=0.0]

[np.float64(0.20848230901135412),
 np.float64(0.22423312114596786),
 np.float64(0.3260725473572642),
 np.float64(0.1936138325018864),
 np.float64(0.28211207089546736),
 np.float64(0.4030575799326874),
 np.float64(0.28149157534932834),
 np.float64(0.4158878540114358),
 np.float64(0.32981405353795584),
 np.float64(0.3992804210453634)]

In [721]:
df1 = pd.DataFrame(vec)

In [722]:
df1

0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5567  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5568  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5569  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5570  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5571  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      493  494  495  496  497  498  499  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
5567  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5568  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5569  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5570  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5571  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5572 rows x 500 columns]

In [723]:
df1[i].unique() == 0.0

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [724]:
zero_columns = [col for col in df1.columns if df1[col].nunique() == 1]
print(zero_columns)  # List of column names that have only 0.0


[]


In [725]:
df1[0].nunique()

27

In [726]:
import xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [727]:
x = df1
y = df['v1']

In [728]:
y = y.map({'ham': 1, 'spam': 0})
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: v1, Length: 5572, dtype: int64


In [729]:
from imblearn.under_sampling import RandomUnderSampler

X_resampled, y_resampled = RandomUnderSampler().fit_resample(x, y)


In [730]:
x_train,x_test,y_train,y_test = train_test_split(X_resampled, y_resampled,test_size=0.2,random_state=42)

In [731]:
y_train

3996    0
3999    0
813     1
3677    0
1441    1
       ..
2885    1
4406    1
2517    1
2673    1
4307    1
Name: v1, Length: 1195, dtype: int64

In [732]:
xgb = XGBClassifier()
xgb.fit(x_train,y_train)

train_pred = xgb.predict(x_train)
test_pred = xgb.predict(x_test)

In [733]:
print(classification_report(y_train,train_pred))
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       602
           1       0.99      1.00      1.00       593

    accuracy                           1.00      1195
   macro avg       1.00      1.00      1.00      1195
weighted avg       1.00      1.00      1.00      1195

              precision    recall  f1-score   support

           0       0.94      0.92      0.93       145
           1       0.93      0.95      0.94       154

    accuracy                           0.94       299
   macro avg       0.94      0.94      0.94       299
weighted avg       0.94      0.94      0.94       299



In [734]:
dtree = DecisionTreeClassifier()
dtree.fit(x_train,y_train)

train_pred = dtree.predict(x_train)
test_pred = dtree.predict(x_test)

In [735]:
print(classification_report(y_train,train_pred))
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       602
           1       1.00      1.00      1.00       593

    accuracy                           1.00      1195
   macro avg       1.00      1.00      1.00      1195
weighted avg       1.00      1.00      1.00      1195

              precision    recall  f1-score   support

           0       0.90      0.92      0.91       145
           1       0.92      0.91      0.92       154

    accuracy                           0.91       299
   macro avg       0.91      0.91      0.91       299
weighted avg       0.91      0.91      0.91       299



In [736]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

train_pred = lr.predict(x_train)
test_pred = lr.predict(x_test)

In [737]:
print(classification_report(y_train,train_pred))
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       602
           1       0.95      0.98      0.96       593

    accuracy                           0.96      1195
   macro avg       0.96      0.96      0.96      1195
weighted avg       0.96      0.96      0.96      1195

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       145
           1       0.96      0.97      0.96       154

    accuracy                           0.96       299
   macro avg       0.96      0.96      0.96       299
weighted avg       0.96      0.96      0.96       299



In [738]:
y_test.value_counts()

v1
1    154
0    145
Name: count, dtype: int64

In [739]:
data = input("Enter your Message to check whether it is spam or not spam")


In [740]:
newdata = []
lmtz = WordNetLemmatizer()

data = re.sub(r'[^a-zA-Z]', ' ', data.lower())  # Remove non-alphabetic characters
data = data.split()  # Split into words
lemmatized_words = [lmtz.lemmatize(word, pos='v') for word in data]  # Lemmatize all words as verbs
newdata.append(" ".join(lemmatized_words))  # Join words back into a sentence

newdata  # Print first processed text
tfidf_data = tfidf.transform(newdata)

In [741]:
pred = xgb.predict(tfidf_data)
pred

array([0])

In [742]:
tfidf.get_feature_names_out()

array(['able', 'about', 'abt', 'account', 'actually', 'after',
       'afternoon', 'again', 'age', 'ah', 'aight', 'all', 'already',
       'alright', 'also', 'always', 'amp', 'an', 'and', 'another',
       'answer', 'any', 'anything', 'anyway', 'apply', 'around', 'as',
       'ask', 'at', 'attempt', 'await', 'award', 'away', 'babe', 'baby',
       'back', 'bad', 'be', 'because', 'bed', 'before', 'best', 'better',
       'between', 'big', 'birthday', 'bite', 'book', 'bore', 'box', 'boy',
       'break', 'bring', 'bt', 'bus', 'but', 'buy', 'by', 'call',
       'camera', 'can', 'cant', 'car', 'care', 'cash', 'chance', 'change',
       'charge', 'chat', 'check', 'claim', 'class', 'close', 'co', 'code',
       'collect', 'collection', 'colour', 'com', 'come', 'contact',
       'cool', 'cos', 'cost', 'could', 'credit', 'cs', 'customer', 'da',
       'dad', 'dat', 'date', 'day', 'days', 'de', 'dear', 'decide',
       'decimal', 'den', 'detail', 'didn', 'didnt', 'dinner', 'dis', 'do',
       '